### ISSUE TITLE
propertyName

### ISSUE THREAD

**Issue by EasonHolmes** [fishCoder/FloatActionButtonExpand#1]
ObjectAnimator.ofInt(this, "currentRadius", expand ? 0 : endRadius, expand ? endRadius : 0) 请问currentRadius这个是如何定义的？

**Comment by fishCoder** [comment]
currentRadius 是 BaseLayout 的成员变量，并且有一个set方法。 ObjectAnimator.ofInt 会根据"currentRadius" 反射调用currentRadius的set方法。
然后 在动画执行过程中，将currentRadius值从第三个参数渐变到第四个参数。

**Comment by EasonHolmes** [comment]
@fishCoder thank you so much!!

**Comment by EasonHolmes** [comment]
十分感谢。学习了

2016-12-02 17:50 GMT+08:00 fulongbin <notifications@github.com>:

**Comment by fishCoder** [comment]
^_^
